name: antonella
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dartz: ^0.10.1
  dio: ^5.7.0
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.2
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  hive_flutter: ^1.1.0
  lottie: ^3.1.3
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  top_snackbar_flutter: ^3.1.0
  flutter_secure_storage: ^9.2.2
  percent_indicator: ^4.2.4
  equatable: ^2.0.7
  awesome_dialog: ^3.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.2
  flutter_gen: ^5.10.0
  smooth_page_indicator: ^1.2.1
  circle_nav_bar: ^2.2.0
  dropdown_search: ^6.0.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  numberpicker: ^2.1.2
  flutter_time_picker_spinner: ^2.0.0
  flutter_image_compress: ^2.4.0
  image: ^4.5.4
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  chat_bubbles: ^1.6.0
  flutter_local_notifications: ^19.3.0
  firebase_messaging: ^15.2.9
  firebase_core: ^3.15.1
  permission_handler: ^12.0.1
  image_cropper: ^9.1.0
  webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5
  flip_card: ^0.7.0
  patterns_canvas: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
  - .env
  - assets/icon/
  - assets/logo/
  - assets/lottie/
  - assets/img/
  - assets/svg/
